import type { Metadata } from "next";
import { Lexend } from "next/font/google";
import "@/app/main.css";
import Link from "next/link";
import Image from "next/image";

const lexendFont = Lexend({
  variable: "--lexend-font",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lexendFont.variable} ${lexendFont.variable} antialiased`}>
        <div className='flex flex-row overflow-hidden bg-wiki-background-color h-screen w-screen p-4 gap-3 flex-shrink-0'>
          {/* Navbar */}
          <nav className='flex flex-col overflow-hidden w-wiki-sidebar-full gap-3'>
            <Link href={"/"} className='rounded-wiki border-wiki px-4 py-3' draggable={false}><Image width={100} height={100} src='/wikilogo.svg' className='w-full h-full pointer-events-none' draggable={false} alt="Wiki Logo" /></Link>
            <div className='flex flex-col gap-3 p-4 border rounded-wiki border-wiki border-wiki-hud-elements-color'>
              paths
            </div>
          </nav>
          {/* Content */}
          <main className='bg-wiki-foreground-color rounded-wiki border-wiki border-wiki-border-color w-full h-full px-12 pt-8 pb-12 overflow-scroll'>
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
