import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/main.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className='flex flex-row overflow-hidden bg-wiki-background-color h-screen w-screen p-4 gap-3 flex-shrink-0'>
          {/* Navbar */}
          <nav className='flex flex-col overflow-hidden w-wiki-sidebar-full gap-3'>
            <div className='flex flex-col gap-3 p-4 border rounded-wiki border-wiki border-wiki-hud-elements-color'>
              paths
            </div>
          </nav>
          {/* Content */}
          <main className='bg-wiki-foreground-color rounded-wiki border-wiki border-wiki-border-color w-full'>
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
