/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as PagesTestIndexImport } from './routes/_pages/test/index'
import { Route as PagesLinuxIndexImport } from './routes/_pages/linux/index'
import { Route as PagesDevelopmentIndexImport } from './routes/_pages/development/index'
import { Route as PagesLinuxInstallkvmIndexImport } from './routes/_pages/linux/install_kvm/index'
import { Route as PagesDevelopmentNestedtestIndexImport } from './routes/_pages/development/nestedtest/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PagesTestIndexRoute = PagesTestIndexImport.update({
  id: '/_pages/test/',
  path: '/test/',
  getParentRoute: () => rootRoute,
} as any)

const PagesLinuxIndexRoute = PagesLinuxIndexImport.update({
  id: '/_pages/linux/',
  path: '/linux/',
  getParentRoute: () => rootRoute,
} as any)

const PagesDevelopmentIndexRoute = PagesDevelopmentIndexImport.update({
  id: '/_pages/development/',
  path: '/development/',
  getParentRoute: () => rootRoute,
} as any)

const PagesLinuxInstallkvmIndexRoute = PagesLinuxInstallkvmIndexImport.update({
  id: '/_pages/linux/install_kvm/',
  path: '/linux/install_kvm/',
  getParentRoute: () => rootRoute,
} as any)

const PagesDevelopmentNestedtestIndexRoute =
  PagesDevelopmentNestedtestIndexImport.update({
    id: '/_pages/development/nestedtest/',
    path: '/development/nestedtest/',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_pages/development/': {
      id: '/_pages/development/'
      path: '/development'
      fullPath: '/development'
      preLoaderRoute: typeof PagesDevelopmentIndexImport
      parentRoute: typeof rootRoute
    }
    '/_pages/linux/': {
      id: '/_pages/linux/'
      path: '/linux'
      fullPath: '/linux'
      preLoaderRoute: typeof PagesLinuxIndexImport
      parentRoute: typeof rootRoute
    }
    '/_pages/test/': {
      id: '/_pages/test/'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof PagesTestIndexImport
      parentRoute: typeof rootRoute
    }
    '/_pages/development/nestedtest/': {
      id: '/_pages/development/nestedtest/'
      path: '/development/nestedtest'
      fullPath: '/development/nestedtest'
      preLoaderRoute: typeof PagesDevelopmentNestedtestIndexImport
      parentRoute: typeof rootRoute
    }
    '/_pages/linux/install_kvm/': {
      id: '/_pages/linux/install_kvm/'
      path: '/linux/install_kvm'
      fullPath: '/linux/install_kvm'
      preLoaderRoute: typeof PagesLinuxInstallkvmIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/development': typeof PagesDevelopmentIndexRoute
  '/linux': typeof PagesLinuxIndexRoute
  '/test': typeof PagesTestIndexRoute
  '/development/nestedtest': typeof PagesDevelopmentNestedtestIndexRoute
  '/linux/install_kvm': typeof PagesLinuxInstallkvmIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/development': typeof PagesDevelopmentIndexRoute
  '/linux': typeof PagesLinuxIndexRoute
  '/test': typeof PagesTestIndexRoute
  '/development/nestedtest': typeof PagesDevelopmentNestedtestIndexRoute
  '/linux/install_kvm': typeof PagesLinuxInstallkvmIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_pages/development/': typeof PagesDevelopmentIndexRoute
  '/_pages/linux/': typeof PagesLinuxIndexRoute
  '/_pages/test/': typeof PagesTestIndexRoute
  '/_pages/development/nestedtest/': typeof PagesDevelopmentNestedtestIndexRoute
  '/_pages/linux/install_kvm/': typeof PagesLinuxInstallkvmIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/development'
    | '/linux'
    | '/test'
    | '/development/nestedtest'
    | '/linux/install_kvm'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/development'
    | '/linux'
    | '/test'
    | '/development/nestedtest'
    | '/linux/install_kvm'
  id:
    | '__root__'
    | '/'
    | '/_pages/development/'
    | '/_pages/linux/'
    | '/_pages/test/'
    | '/_pages/development/nestedtest/'
    | '/_pages/linux/install_kvm/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PagesDevelopmentIndexRoute: typeof PagesDevelopmentIndexRoute
  PagesLinuxIndexRoute: typeof PagesLinuxIndexRoute
  PagesTestIndexRoute: typeof PagesTestIndexRoute
  PagesDevelopmentNestedtestIndexRoute: typeof PagesDevelopmentNestedtestIndexRoute
  PagesLinuxInstallkvmIndexRoute: typeof PagesLinuxInstallkvmIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PagesDevelopmentIndexRoute: PagesDevelopmentIndexRoute,
  PagesLinuxIndexRoute: PagesLinuxIndexRoute,
  PagesTestIndexRoute: PagesTestIndexRoute,
  PagesDevelopmentNestedtestIndexRoute: PagesDevelopmentNestedtestIndexRoute,
  PagesLinuxInstallkvmIndexRoute: PagesLinuxInstallkvmIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_pages/development/",
        "/_pages/linux/",
        "/_pages/test/",
        "/_pages/development/nestedtest/",
        "/_pages/linux/install_kvm/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_pages/development/": {
      "filePath": "_pages/development/index.tsx"
    },
    "/_pages/linux/": {
      "filePath": "_pages/linux/index.tsx"
    },
    "/_pages/test/": {
      "filePath": "_pages/test/index.tsx"
    },
    "/_pages/development/nestedtest/": {
      "filePath": "_pages/development/nestedtest/index.tsx"
    },
    "/_pages/linux/install_kvm/": {
      "filePath": "_pages/linux/install_kvm/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
