/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as PagesTestIndexImport } from './routes/_pages/test/index'
import { Route as PagesHomecloudIndexImport } from './routes/_pages/homecloud/index'
import { Route as PagesHomecloudInstallkvmIndexImport } from './routes/_pages/homecloud/install_kvm/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PagesTestIndexRoute = PagesTestIndexImport.update({
  id: '/_pages/test/',
  path: '/test/',
  getParentRoute: () => rootRoute,
} as any)

const PagesHomecloudIndexRoute = PagesHomecloudIndexImport.update({
  id: '/_pages/homecloud/',
  path: '/homecloud/',
  getParentRoute: () => rootRoute,
} as any)

const PagesHomecloudInstallkvmIndexRoute =
  PagesHomecloudInstallkvmIndexImport.update({
    id: '/_pages/homecloud/install_kvm/',
    path: '/homecloud/install_kvm/',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_pages/homecloud/': {
      id: '/_pages/homecloud/'
      path: '/homecloud'
      fullPath: '/homecloud'
      preLoaderRoute: typeof PagesHomecloudIndexImport
      parentRoute: typeof rootRoute
    }
    '/_pages/test/': {
      id: '/_pages/test/'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof PagesTestIndexImport
      parentRoute: typeof rootRoute
    }
    '/_pages/homecloud/install_kvm/': {
      id: '/_pages/homecloud/install_kvm/'
      path: '/homecloud/install_kvm'
      fullPath: '/homecloud/install_kvm'
      preLoaderRoute: typeof PagesHomecloudInstallkvmIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/homecloud': typeof PagesHomecloudIndexRoute
  '/test': typeof PagesTestIndexRoute
  '/homecloud/install_kvm': typeof PagesHomecloudInstallkvmIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/homecloud': typeof PagesHomecloudIndexRoute
  '/test': typeof PagesTestIndexRoute
  '/homecloud/install_kvm': typeof PagesHomecloudInstallkvmIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_pages/homecloud/': typeof PagesHomecloudIndexRoute
  '/_pages/test/': typeof PagesTestIndexRoute
  '/_pages/homecloud/install_kvm/': typeof PagesHomecloudInstallkvmIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/homecloud' | '/test' | '/homecloud/install_kvm'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/homecloud' | '/test' | '/homecloud/install_kvm'
  id:
    | '__root__'
    | '/'
    | '/_pages/homecloud/'
    | '/_pages/test/'
    | '/_pages/homecloud/install_kvm/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PagesHomecloudIndexRoute: typeof PagesHomecloudIndexRoute
  PagesTestIndexRoute: typeof PagesTestIndexRoute
  PagesHomecloudInstallkvmIndexRoute: typeof PagesHomecloudInstallkvmIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PagesHomecloudIndexRoute: PagesHomecloudIndexRoute,
  PagesTestIndexRoute: PagesTestIndexRoute,
  PagesHomecloudInstallkvmIndexRoute: PagesHomecloudInstallkvmIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_pages/homecloud/",
        "/_pages/test/",
        "/_pages/homecloud/install_kvm/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_pages/homecloud/": {
      "filePath": "_pages/homecloud/index.tsx"
    },
    "/_pages/test/": {
      "filePath": "_pages/test/index.tsx"
    },
    "/_pages/homecloud/install_kvm/": {
      "filePath": "_pages/homecloud/install_kvm/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
