/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as PagesTestdir1IndexImport } from './routes/_pages/testdir1/index'
import { Route as PagesTestdir1Testdir12IndexImport } from './routes/_pages/testdir1/testdir12/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PagesTestdir1IndexRoute = PagesTestdir1IndexImport.update({
  id: '/_pages/testdir1/',
  path: '/testdir1/',
  getParentRoute: () => rootRoute,
} as any)

const PagesTestdir1Testdir12IndexRoute =
  PagesTestdir1Testdir12IndexImport.update({
    id: '/_pages/testdir1/testdir12/',
    path: '/testdir1/testdir12/',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_pages/testdir1/': {
      id: '/_pages/testdir1/'
      path: '/testdir1'
      fullPath: '/testdir1'
      preLoaderRoute: typeof PagesTestdir1IndexImport
      parentRoute: typeof rootRoute
    }
    '/_pages/testdir1/testdir12/': {
      id: '/_pages/testdir1/testdir12/'
      path: '/testdir1/testdir12'
      fullPath: '/testdir1/testdir12'
      preLoaderRoute: typeof PagesTestdir1Testdir12IndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/testdir1': typeof PagesTestdir1IndexRoute
  '/testdir1/testdir12': typeof PagesTestdir1Testdir12IndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/testdir1': typeof PagesTestdir1IndexRoute
  '/testdir1/testdir12': typeof PagesTestdir1Testdir12IndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_pages/testdir1/': typeof PagesTestdir1IndexRoute
  '/_pages/testdir1/testdir12/': typeof PagesTestdir1Testdir12IndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/testdir1' | '/testdir1/testdir12'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/testdir1' | '/testdir1/testdir12'
  id: '__root__' | '/' | '/_pages/testdir1/' | '/_pages/testdir1/testdir12/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PagesTestdir1IndexRoute: typeof PagesTestdir1IndexRoute
  PagesTestdir1Testdir12IndexRoute: typeof PagesTestdir1Testdir12IndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PagesTestdir1IndexRoute: PagesTestdir1IndexRoute,
  PagesTestdir1Testdir12IndexRoute: PagesTestdir1Testdir12IndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_pages/testdir1/",
        "/_pages/testdir1/testdir12/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_pages/testdir1/": {
      "filePath": "_pages/testdir1/index.tsx"
    },
    "/_pages/testdir1/testdir12/": {
      "filePath": "_pages/testdir1/testdir12/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
