name: Publish Wiki

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment: 
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    name: Build & Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Init Node
        uses: actions/setup-node@v4
      - name: Init Python        
        uses: actions/setup-python@v5
      - name: NPM Install
        run: npm ci
      - name: Initialize Wiki
        run: npm run init
      - name: NPM Build
        run: npm run build
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v4
      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist
      - name: Deploy/Publish to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        
