# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deploy Wiki

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Init Node
        uses: actions/setup-node@v4
      - name: NPM Install
        run: npm ci
      - name: NPM Build
        run: npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: ./dist
  deploy:
    if: github.ref == "refs/heads/main"
    name: Deploy
    runs-on: ubuntu-latest
    needs: build

    permissions:
      pages: write
      id-token: write

    environment: 
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Pull artifacts
        uses: actions/download-artifact@v4
        with: 
          name: artifacts
          path: ./dist
      - name: Deploy/Publish to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        
